version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: infinite_clinic_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: infinite_clinic_db
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet

volumes:
  mongodb_data:
